#!/bin/sh

set -e

if [ "$1" = "configure" ] && [ -x /etc/init.d/brickd ]; then
	update-rc.d brickd defaults > /dev/null

	if [ -x /usr/sbin/invoke-rc.d ]; then
		invoke-rc.d brickd start
	else
		/etc/init.d/brickd start
	fi
fi

if [ "$1" = "configure" ] && [ -d /run/systemd/system ] && [ -e /lib/systemd/system/brickd-resume.service ]; then
	systemctl enable brickd-resume.service
fi

exit 0
