#!/bin/sh

# https://wiki.debian.org/MaintainerScripts

set -e

if [ "$1" = "configure" ]; then
	if [ -d /run/systemd/system ]; then
		systemctl enable brickd.service
		systemctl start brickd.service
	else
		cp /usr/share/brickd/brickd-sysv-init /etc/init.d/brickd
		update-rc.d brickd defaults >/dev/null

		if [ -x /usr/sbin/invoke-rc.d ]; then
			invoke-rc.d brickd start
		else
			/etc/init.d/brickd start
		fi
	fi

	if [ -d /run/systemd/system ]; then
		systemctl enable brickd-resume.service
	fi
fi

exit 0
