#!/bin/sh

# https://wiki.debian.org/MaintainerScripts

set -e

if [ "$1" = "remove" ]; then
	if [ -d /run/systemd/system ]; then
		systemctl disable brickd.service
		systemctl disable brickd-resume.service
	else
		update-rc.d brickd remove >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	rm /etc/init.d/brickd || true
	rm -f /var/log/brickd.log*
fi

exit 0
