#!/bin/sh

# https://wiki.debian.org/MaintainerScripts

set -e

# clean up properly before installing the new brickd. in a perfect world this
# should not be necessary and the prerm script from the old brickd should clean
# up properly behind itself. but not all old brickd versions did this properly
if [ "$1" = "upgrade" ]; then
	PID=$(pgrep -F /var/run/brickd.pid -L brickd 2>/dev/null || pgrep brickd 2>/dev/null || true)

	if [ -n "${PID:-}" ]; then
		if [ -d /run/systemd/system ]; then
			systemctl stop brickd.service
		elif [ -x /etc/init.d/brickd ]; then
			if [ -x /usr/sbin/invoke-rc.d ]; then
				invoke-rc.d brickd stop
			else
				/etc/init.d/brickd stop
			fi
		fi
	fi

	rm /etc/init.d/brickd 2>/dev/null || true

	if [ -x /usr/sbin/update-rc.d ]; then
		update-rc.d brickd remove >/dev/null
	fi
fi

exit 0
