#!/bin/sh

# https://wiki.debian.org/MaintainerScripts

set -e

if [ "$1" = "remove" ] || [ "$1" = "upgrade" ]; then
	PID=$(pgrep -F /var/run/brickd.pid -L brickd 2>/dev/null || pgrep brickd 2>/dev/null || true)

	if [ -n "${PID:-}" ]; then
		if [ -d /run/systemd/system ]; then
			systemctl stop brickd.service
		else
			if [ -x /usr/sbin/invoke-rc.d ]; then
				invoke-rc.d brickd stop
			else
				/etc/init.d/brickd stop
			fi
		fi
	fi

	if [ -d /run/systemd/system ]; then
		systemctl disable brickd.service
		systemctl disable brickd-resume.service
	fi
fi

exit 0
