#!/bin/sh -e

PIDFILE=/var/run/brickd.pid

if [ -x /etc/init.d/brickd ]
then
	if [ -n "${PIDFILE:-}" -a -r "$PIDFILE" ]; then
		PID=`cat "$PIDFILE"`
		if [ -n "${PID:-}" ]; then
			if $(kill -0 "${PID:-}" 2> /dev/null); then
				/etc/init.d/brickd stop
			elif ps "${pid:-}" > /dev/null 2>&1; then
				/etc/init.d/brickd stop
			fi
		fi
	fi
fi

if [ -x /usr/sbin/update-rc.d ]
then
	/usr/sbin/update-rc.d -f brickd remove
fi
